name: UI Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./Example

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Force Xcode 11
        run: sudo xcode-select -switch /Applications/Xcode_11.3.app
      - name: Test
        run: |
          pwd
          xcodebuild test -scheme TestApplication -workspace TestApplication.xcworkspace -destination "platform=iOS Simulator,name=iPhone 13"
