name: UI Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./Example

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - name: Xcode Select
        uses: devbotsxyz/xcode-select@v1.1.0
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          xcodebuild test -scheme TestApplication -workspace TestApplication.xcworkspace -destination "platform=iOS Simulator,name=iPhone 13"
