name: UI Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

defaults:
  run:
    working-directory: ./Example

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-latest

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
          with:
            xcode-version: '13.1'
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        run: |
          xcodebuild test -scheme TestApplication -workspace TestApplication.xcworkspace -destination "platform=iOS Simulator,name=iPhone 13"
